import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../../../globals.css";
import Header from "./_components/header";
import { AppSidebar } from "./_components/sidebar";
import { getUser } from "@/lib/auth";
import { redirect } from "next/navigation";

import {
  SidebarInset,
  SidebarProvider,
} from "@/components/ui/sidebar";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Admin Dashboard",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { session } = await getUser();

  if (!session) {
    return redirect("/dashboard/sign-in");
  }

  return (
    <html lang="en">
			<body className={inter.className}>
				<SidebarProvider className="dark">
          <AppSidebar/>
          <SidebarInset>
              <Header />
              <main className="py-4 px-6">
                {children}
              </main>
          </SidebarInset>
        </SidebarProvider>
			</body>
		</html>
  );
}
